[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt", "npm ci"]

[phases.build]
cmds = ["chmod +x ./build.sh", "./build.sh"]

[start]
cmd = "python -m gunicorn ecm_website.wsgi:application -k uvicorn.workers.UvicornWorker"
